package org.flamingo.gray.agent.plugin.gray.rule;

import java.util.ArrayList;
import java.util.List;

public class GrayRule {


    private Integer id;
    private Integer planId;
    private Integer pathId;
    private String paramType;
    private String paramName;
    private String paramValue;
    private String comparator;

    private List<String> paramValueList = new ArrayList<>();
    private List<Double> paramRangeList = new ArrayList<>();
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gray_rule.id
     *
     * @return the value of gray_rule.id
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gray_rule.id
     *
     * @param id the value for gray_rule.id
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gray_rule.plan_id
     *
     * @return the value of gray_rule.plan_id
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gray_rule.plan_id
     *
     * @param planId the value for gray_rule.plan_id
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gray_rule.path_id
     *
     * @return the value of gray_rule.path_id
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public Integer getPathId() {
        return pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gray_rule.path_id
     *
     * @param pathId the value for gray_rule.path_id
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public void setPathId(Integer pathId) {
        this.pathId = pathId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gray_rule.param_type
     *
     * @return the value of gray_rule.param_type
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gray_rule.param_type
     *
     * @param paramType the value for gray_rule.param_type
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public void setParamType(String paramType) {
        this.paramType = paramType == null ? null : paramType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gray_rule.param_name
     *
     * @return the value of gray_rule.param_name
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gray_rule.param_name
     *
     * @param paramName the value for gray_rule.param_name
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gray_rule.param_value
     *
     * @return the value of gray_rule.param_value
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gray_rule.param_value
     *
     * @param paramValue the value for gray_rule.param_value
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gray_rule.comparator
     *
     * @return the value of gray_rule.comparator
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public String getComparator() {
        return comparator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gray_rule.comparator
     *
     * @param comparator the value for gray_rule.comparator
     *
     * @mbg.generated Mon Aug 26 18:10:43 CST 2019
     */
    public void setComparator(String comparator) {
        this.comparator = comparator == null ? null : comparator.trim();
    }

    public List<String> getParamValueList() {
        return paramValueList;
    }

    public void setParamValueList(List<String> paramValueList) {
        this.paramValueList = paramValueList;
    }

    public List<Double> getParamRangeList() {
        return paramRangeList;
    }

    public void setParamRangeList(List<Double> paramRangeList) {
        this.paramRangeList = paramRangeList;
    }
}